"""Added role field to user profile table

Revision ID: 1c5422ac3254
Revises: 6467a9aea1e7
Create Date: 2025-02-06 10:04:45.754521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c5422ac3254'
down_revision: Union[str, None] = '6467a9aea1e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    userrole_enum = sa.Enum('NORMAL', 'ADMIN', 'SUPER_ADMIN', name='userrole')
    userrole_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('userprofiles', sa.Column('role', userrole_enum, nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('userprofiles', 'role')
    userrole_enum = sa.Enum('NORMAL', 'ADMIN', 'SUPER_ADMIN', name='userrole')
    userrole_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
